{{- if .Values.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend-api
  namespace: {{ .Release.Namespace }}
  annotations:
    # THIS IS THE KEY FIX:
    # It takes the path captured in the 2nd group (.*) and uses that as the new path.
    # Effectively: /api/signup -> /signup
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          # Regex to match "/api" followed by anything else
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-backend-proxy
                port:
                  number: 8000
{{- end }}